name: Build and Push Docker image to GHCR

on:
  push:
    branches:
      - main  # Trigger action on push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Runs the workflow on the latest Ubuntu image
    
    permissions:
      contents: read
      packages: write
      
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHub username
          password: ${{ secrets.GITHUB_TOKEN }}  # Uses the default GitHub token

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} .
        
      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

